### ISSUE TITLE
Option to disable url appending hash

### ISSUE THREAD

**Issue by angelinekwan** [pettiboy/react-ui-scrollspy#5]
Could you advice how to disable the page url from appending active section as hash?
The reason is because the page has other section (hero) that is not part of the scrollspy `<ScrollSpy>` .
This cause the page when load to scroll directly to the 1st ScrollSpy element and skipping the rest of the page content.
```
<hero /> -> height 90vh
<nav />
<ScrollSpy>
<div>
<div>
<ScrollSpy>
```

Thanks in advance.

**Comment by iamanwar94** [comment]
add this attribute  useDataAttribute=""
 <ScrollSpy 
                
                useDataAttribute=""
               
            >
               
            </ScrollSpy>

**Comment by iamanwar94** [comment]
add this attribute useDataAttribute=""

**Comment by GuilhermeRaposo** [comment]
Had a similar problem, this should help #10
